### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by venatiodecorus** [ninjadev/nin#519]
I run `sudo npm install -g ninjadev-nin` and I get the following output:

```
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
/usr/local/bin/nin -> /usr/local/lib/node_modules/ninjadev-nin/nin/backend/nin

> jpegtran-bin@3.2.0 postinstall /usr/local/lib/node_modules/ninjadev-nin/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ninjadev-nin/node_modules/jpegtran-bin/vendor'
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
/usr/local/lib/node_modules/ninjadev-nin/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				^

Error: callback() can only be called once.
    at onetime (/usr/local/lib/node_modules/ninjadev-nin/node_modules/onetime/index.js:15:11)
    at /usr/local/lib/node_modules/ninjadev-nin/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/ninjadev-nin/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:198:15)
    at finishMaybe (/usr/local/lib/node_modules/ninjadev-nin/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/usr/local/lib/node_modules/ninjadev-nin/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at ConcatStream.Writable.end (/usr/local/lib/node_modules/ninjadev-nin/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DuplexWrapper.onend (/usr/local/lib/node_modules/ninjadev-nin/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:281:20)
    at DuplexWrapper.emit (events.js:198:15)
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-errors@1.0.1 requires a peer of ajv@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/ninjadev-nin/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jpegtran-bin@3.2.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jpegtran-bin@3.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/octo/.npm/_logs/2019-04-26T23_05_11_875Z-debug.log
```

**Comment by venatiodecorus** [comment]
```
node --version
v11.14.0

npm version
{ npm: '6.9.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '34.0',
  http_parser: '2.8.0',
  icu: '63.1',
  llhttp: '1.1.1',
  modules: '67',
  napi: '4',
  nghttp2: '1.37.0',
  node: '11.14.0',
  openssl: '1.1.1b',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.27.0',
  v8: '7.0.276.38-node.18',
  zlib: '1.2.11' }

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
```

**Comment by iver56** [comment]
Perhaps this trick helps?
https://github.com/imagemin/imagemin/issues/256#issuecomment-347462755

**Comment by venatiodecorus** [comment]
Thanks yeah that worked
